# Generated by Django 2.0.4 on 2018-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapp', '0002_auto_20180630_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicer',
            name='password',
            field=models.CharField(default='12345678', max_length=15),
        ),
    ]
